### ISSUE TITLE
AttributeError: module 'pyConTextNLP.itemData' has no attribute 'instantiateFromCSVtoitemData'

### ISSUE THREAD

**Issue by quzhouxiachuan** [chapmanbe/pyConTextNLP#11]
I installed pyChonTextNLP successfully. However, when using the following command: 

```
 mod = itemData.instantiateFromCSVtoitemData(
    "https://raw.githubusercontent.com/chapmanbe/pyConTextNLP/master/KB/lexical_kb_05042016.tsv")
```
It shows the following error message: 
AttributeError: module 'pyConTextNLP.itemData' has no attribute 'instantiateFromCSVtoitemData'

Could you please help with that? 

Thanks!

**Comment by chapmanbe** [comment]
Since we moved to using YAML files rather than csv or txt files, I dropped that function. I will add it back over the weekend. In the meantime, you could find the code in a previous version of pyConTextNLP.

Sorry for this.

Brian

**Comment by chapmanbe** [comment]
Everything should be working for you now if you install the latest version from pypi or clone and install from github

**Comment by quzhouxiachuan** [comment]
Thanks so much!
